version: "3.3"

services:
  database:
    image: sebirhz/resplan-database:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: database
    volumes:
      - ./dockervolume:/var/lib/mysql
    ports:
    - 3306:3306

    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPASS}


  nestbackend:
    image: sebirhz/resplan-backend:latest
    container_name: nestbackend
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - 3000:3000
    links:
      - database


  anuglarfrontend:
    image: sebirhz/resplan-frontend:latest
    container_name: anuglarfrontend
    depends_on:
      - database
      - nestbackend
    ports:
      - 80:80
    links:
      - nestbackend
