name: Docker Images

on:
    pull_request:
        branches:
        - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: docker login
              env:
                DOCKER_USER: ${{secrets.DOCKER_USER}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build database image
              run: cd frontend && docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/resplan-frontend:$(date +%s)

            - name: Docker push database image
              run: docker push ${{secrets.DOCKER_USER}}/resplan-frontend:$(date +%s)
