name: Docker Images

on:
    pull_request:
        branches:
        - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: docker login
              env:
                DOCKER_USER: ${{secrets.DOCKER_USER}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build frontend image
              run: cd frontend && docker build . --file Dockerfile --tag sebirhz/resplan-frontend:test

            - name: Docker push frontend image
              run: docker push sebirhz/resplan-frontend:test
