name: Master-Build-Backend

on:
  push:
    branches:
    - master
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
    - master
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd backend/ && npm ci
      - run: cd backend/ && npm run test
#        todo: e2e tests
#      - run: cd backend/ && npm run test:e2e
