name: Develop-Build-Frontend

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
    - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_SCHEMA: test_db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: ${{ secrets.ROOTPASSWORD }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '5.7'
          mysql database: 'test_db'
          mysql root password: ${{ secrets.ROOTPASSWORD }}
          mysql user: ''
          mysql password: ''
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: backend
        uses: docker://sebirhz/resplan-backend:latest
      - run: cd frontend/ && npm ci
      - run: cd frontend/ && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      - run: cd frontend/ && npm run start & cd frontend/ && npm run cy:run
