name: Develop-Build

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
    - develop
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_SCHEMA: test_db
      DATABASE_USER: root
      DATABASE_PASSWORD: root

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: haltuf/mysql-action@master
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'test_db'
          mysql root password: ${{ secrets.ROOTPASSWORD }}
          mysql user: ''
          mysql password: ''
          authentication plugin: 'mysql_native_password'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install backend
        run: cd backend/ && npm ci
      - name: Run backend unit tests
        run: cd backend/ && npm run test
      - name: Run backend e2e test
        run: cd backend/ && npm run test:e2e
      - name: Install frontend
        run: cd frontend/ && npm ci
      - name: Run frontend unit tests
        run: cd frontend/ && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      - name: Run frontend e2e tests
        run: cd backend/ && npm run start & cd frontend/ && npm run start & cd frontend/ && npm run cy:run
